command_timeout = 100
scan_timeout = 1000

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname]($style):"

[directory]
truncation_length = 3
truncate_to_repo = false

[golang]
detect_files = ["go.mod"]
detect_folders = []

[docker_context]
format = " [$context]($style)"
only_with_files = true

[kubernetes]
disabled = true
format = " [$symbol$context( \\($namespace\\))]($style)"

[git_status]
disabled = false
